<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sign_in_with_email_button</name>
   <tag></tag>
   <elementGuidId>fc4a5dc4-cc0f-4998-85c9-52556578756f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@data-test-id='home-hero-sign-in-cta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-test-id='home-hero-sign-in-cta']</value>
      <webElementGuid>77061ad1-6ba5-4181-9762-f1c54c629a7f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
